In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1, 3, 4.5, 4])

array([ 1. ,  3. ,  4.5,  4. ])

In [4]:
np.array([1,3,4,5], dtype = 'float32')

array([ 1.,  3.,  4.,  5.], dtype=float32)

In [5]:
np.array([1,2,4,'d'])

array(['1', '2', '4', 'd'], 
      dtype='<U21')

In [7]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5), dtype = float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [10]:
np.random.random((3,3))

array([[ 0.27931622,  0.4034615 ,  0.13239986],
       [ 0.36605953,  0.83149316,  0.69022483],
       [ 0.06679581,  0.75798874,  0.70453572]])

In [11]:
np.random.normal(0, 1, (3,3))

array([[ 0.87680349, -1.24747424, -0.84841763],
       [-0.41100449, -0.20531962,  1.16518374],
       [ 0.76162399, -1.96764442,  0.85639944]])

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
np.random.seed(0)

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [15]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [16]:
print("dtype:", x3.dtype)

dtype: int64


In [20]:
np.arange(1, 10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
x = np.array([1, 2, 3])
print(x)

print(x.reshape((1,3)))

[1 2 3]
[[1 2 3]]


In [3]:
x = np.array([1, 4, 5, 6, 10])
x

array([ 1,  4,  5,  6, 10])

In [5]:
x.sum()

26

In [7]:
np.max(x)

10

In [15]:
x = np.random.random((3,3))
x

array([[ 0.00697049,  0.41165711,  0.30877343],
       [ 0.59080769,  0.05129742,  0.89010753],
       [ 0.32447424,  0.1665424 ,  0.69042898]])

In [16]:
np.min(x, axis = 1)

array([ 0.00697049,  0.05129742,  0.1665424 ])

In [23]:
x + 5

array([[ 5.00697049,  5.41165711,  5.30877343],
       [ 5.59080769,  5.05129742,  5.89010753],
       [ 5.32447424,  5.1665424 ,  5.69042898]])

In [31]:
y = np.array([5, 1, 5])
print(y)
x - y

[5 1 5]


array([[-4.99302951, -0.58834289, -4.69122657],
       [-4.40919231, -0.94870258, -4.10989247],
       [-4.67552576, -0.8334576 , -4.30957102]])

In [32]:
x = np.random.random((10,3))
x

array([[ 0.90635022,  0.45828149,  0.39588864],
       [ 0.33698096,  0.39517955,  0.01476787],
       [ 0.57270127,  0.36690016,  0.48412436],
       [ 0.80039842,  0.44916651,  0.4970161 ],
       [ 0.46291457,  0.52920695,  0.84508014],
       [ 0.05237146,  0.72473678,  0.9524527 ],
       [ 0.60227249,  0.88349459,  0.88736806],
       [ 0.41776771,  0.05036478,  0.52386575],
       [ 0.27952174,  0.74304364,  0.58661705],
       [ 0.57664167,  0.02777816,  0.73528602]])

In [33]:
Xmean = x.mean(0)
Xmean

array([ 0.50079205,  0.46281526,  0.59224667])

In [35]:
Xcentered = x - Xmean
Xcentered.mean(0)

array([  3.33066907e-17,   2.22044605e-17,   5.55111512e-17])